### ISSUE TITLE
trackpad scrolling not working

### ISSUE THREAD

**Issue by mmckegg** [LolaShare/LolaShare.github.io#3]
Can't scroll the page on macOS 10.12.5 using Chrome 60.0.3112.78

**Comment by Marak** [comment]
That's strange, I'm on a similar setup and my trackpad scroll is working.

CC: @wchen71

**Comment by wchen71** [comment]
Im on the exact same set-up and mine is working as well. I'll see if I can look into it

**Comment by mmckegg** [comment]
Strange. I tried turning ublock off. Still not working.

However seems to work fine in Firefox and Safari for me.

**Comment by mmckegg** [comment]
I just reset my chrome://flags back to default and now it is working. Interesting. I must have had some old setting enabled from years ago that was breaking things.

**Comment by mmckegg** [comment]
For the record it was chrome://flags/#enable-experimental-web-platform-features that caused the problem.
